_BASE_: "../base-linear.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "nabirds"
  DATAPATH: "Datasets\\nabirds"  #TODO: need to specify here
  NUMBER_CLASSES: 555
  MULTILABEL: False
MODEL:
  TYPE: "vit"
  WEIGHT_PATH: "vpt\\output\\nabirds\\sup_vitb16\\lr0.0001_wd0.01\\model_v6.pth"
SOLVER:
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.01
  LOG_EVERY_N: 10
  TOTAL_EPOCH: 0